GET http://localhost:3005/init
Content-Type: application/json

{
        "number": 666
    
}




GET http://localhost:3005/events
Content-Type: application/json


GET http://localhost:3005/bookings
Content-Type: application/json